# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0


receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"

exporters:
  otlphttp/aware:
    endpoint: "https://ingress.awarelabs.io"
    headers: {"x-aware-project-id": "344d23af-c8cc-4664-b8cc-4926e29d5f14"}
  otlphttp/awarestaging:
    endpoint: "https://ingress-staging.awarelabs.io"
    headers: {"x-aware-project-id": "dde35739-bdba-4120-b47d-a6ae3712bed5"}
  logging:

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/aware,otlphttp/awarestaging]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]

